// Generated by https://quicktype.io

export interface IDashboardSummaryResponse {
	numberOfClient: number;
	numberOfProduct: number;
	productsWithNoInventory: number;
	numberOfOrders: number;
	paidOrders: number;
	lowInventory: number;
	notPaidOrders: number;
}
